security:
  oauth2:
    client:
      client-id: app-b
      client-secret: app-b-1234
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
server:
  port: 9091
  servlet:
    context-path: /app2